import 'event_model.dart';

class MockEventData {
  static final List<CleanupEvent> events = [
    CleanupEvent(
      id: 'reg_1',
      title: 'Sentosa Coastal Cleanup',
      description: 'Join us for a massive coastal cleanup at Sentosa. We will be clearing plastic debris and fishing nets from the rocky shores to protect marine habitats. All equipment provided.',
      imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80fbea5?auto=format&fit=crop&w=800&q=80',
      organizerName: 'Ocean Protectors SG',
      organizerType: 'NGO',
      latitude: 1.2494,
      longitude: 103.8303,
      address: 'Siloso Beach, Sentosa',
      dateTime: DateTime.now().add(const Duration(days: 2, hours: 4)),
      duration: const Duration(hours: 3),
      maxVolunteers: 100,
      participantsCount: 82,
      ecoPointsReward: 150,
      difficulty: EventDifficulty.moderate,
      type: EventType.beachCleanup,
      status: EventStatus.almostFull,
      distanceKm: 3.2,
      expectedWasteKg: 200,
      requiredItems: ['Water bottle', 'Sunscreen', 'Covered shoes', 'Cap'],
      safetyInstructions: 'Stay away from deep water. Watch out for sharp objects on the beach. Hydrate regularly.',
      participantAvatars: [
        'https://i.pravatar.cc/150?u=1',
        'https://i.pravatar.cc/150?u=2',
        'https://i.pravatar.cc/150?u=3',
      ],
      galleryImages: [
        'https://images.unsplash.com/photo-1594916843477-941d6b0eeefd?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1621451537084-482c73073e0f?auto=format&fit=crop&w=800&q=80',
      ]
    ),
    CleanupEvent(
      id: '2',
      title: 'East Coast Park Drive',
      description: 'Help us clear the weekend trash accumulated along East Coast Park. We will be focusing on the BBQ pit areas and the shoreline.',
      imageUrl: 'https://images.unsplash.com/photo-1583301286816-f4f05e1e8b25?auto=format&fit=crop&w=800&q=80',
      organizerName: 'Green Earth Society',
      organizerType: 'Community Group',
      latitude: 1.3008,
      longitude: 103.9150,
      address: 'East Coast Park Area F',
      dateTime: DateTime.now().add(const Duration(days: 5, hours: 2)),
      duration: const Duration(hours: 2),
      maxVolunteers: 50,
      participantsCount: 20,
      ecoPointsReward: 100,
      difficulty: EventDifficulty.easy,
      type: EventType.beachCleanup,
      status: EventStatus.open,
      distanceKm: 8.5,
      expectedWasteKg: 80,
      requiredItems: ['Water bottle', 'Gloves (optional)'],
      safetyInstructions: 'Beware of cyclists on paths. Wear comfortable clothing.',
      participantAvatars: [
        'https://i.pravatar.cc/150?u=4',
        'https://i.pravatar.cc/150?u=5',
      ],
    ),
    CleanupEvent(
      id: '3',
      title: 'Marina Bay Canal Dive',
      description: 'A challenging dive cleanup targeting sunken debris in the canal area. Only for certified divers.',
      imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
      organizerName: 'Singapore Scuba Alliance',
      organizerType: 'Professional Group',
      latitude: 1.2832,
      longitude: 103.8607,
      address: 'Marina Bay Sands Promenade',
      dateTime: DateTime.now().add(const Duration(days: 10)),
      duration: const Duration(hours: 4),
      maxVolunteers: 20,
      participantsCount: 20,
      ecoPointsReward: 300,
      difficulty: EventDifficulty.challenging,
      type: EventType.canalCleanup,
      status: EventStatus.full,
      distanceKm: 5.1,
      expectedWasteKg: 150,
      requiredItems: ['Diving Certification', 'Scuba Gear', 'Mesh Bag'],
      safetyInstructions: 'Buddy system strictly enforced. Briefing at 8 AM sharp.',
    ),
    CleanupEvent(
      id: 'reg_4',
      title: 'Ocean Plastic Workshop',
      description: 'Educational workshop on upcycling ocean plastics. Learn how to transform collected beach plastic into usable art.',
      imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
      organizerName: 'Eco Schools Network',
      organizerType: 'Schools',
      latitude: 1.2902,
      longitude: 103.8519,
      address: 'National Library Building',
      dateTime: DateTime.now().add(const Duration(days: 1, hours: 5)),
      duration: const Duration(hours: 2),
      maxVolunteers: 40,
      participantsCount: 35,
      ecoPointsReward: 50,
      difficulty: EventDifficulty.easy,
      type: EventType.educationalWorkshop,
      status: EventStatus.open,
      distanceKm: 4.2,
      expectedWasteKg: 0,
      requiredItems: ['Notebook', 'Clean plastics (optional)'],
      safetyInstructions: 'Indoor venue, no special safety gear needed.',
    ),
    CleanupEvent(
      id: '5',
      title: 'Changi Beach Post-Storm Cleanup',
      description: 'Emergency cleanup following the recent storm. Large debris reported along the coastal walk.',
      imageUrl: 'https://images.unsplash.com/photo-1622322083437-08064a39bca4?auto=format&fit=crop&w=800&q=80',
      organizerName: 'Coastal Wardens',
      organizerType: 'Government',
      latitude: 1.3875,
      longitude: 103.9877,
      address: 'Changi Beach Park',
      dateTime: DateTime.now().subtract(const Duration(days: 2)), // Completed
      duration: const Duration(hours: 4),
      maxVolunteers: 150,
      participantsCount: 142,
      ecoPointsReward: 200,
      difficulty: EventDifficulty.moderate,
      type: EventType.beachCleanup,
      status: EventStatus.completed,
      distanceKm: 15.0,
      expectedWasteKg: 450,
      galleryImages: [
        'https://images.unsplash.com/photo-1618477461853-cf6ed80fbea5?auto=format&fit=crop&w=800&q=80',
      ]
    ),
  ];

  static List<CleanupEvent> get upcomingEvents => 
      events.where((e) => e.status != EventStatus.completed).toList();

  static List<CleanupEvent> get completedEvents => 
      events.where((e) => e.status == EventStatus.completed).toList();
      
  static List<CleanupEvent> get registeredEvents => 
      events.where((e) => e.isRegistered && e.status != EventStatus.completed).toList();
}
