import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../../domain/models/map_marker_model.dart';

// ──────────────────────────────────────────────
// Sample mock data for the map
// ──────────────────────────────────────────────
class MockMapData {
  // Centre around Singapore as a default demo location
  static const LatLng defaultCenter = LatLng(1.3521, 103.8198);

  static const List<OceanMapMarker> markers = [
    // ── Pollution reports ──
    OceanMapMarker(
      id: 'p1',
      title: 'East Coast Beach',
      subtitle: 'Critical plastic accumulation',
      position: LatLng(1.3008, 103.9150),
      type: MarkerType.pollution,
      severity: PollutionSeverity.critical,
      status: ReportStatus.verified,
      wasteTypes: [WasteType.plasticBottles, WasteType.plasticBags],
      estimatedWasteKg: 145,
      volunteers: 0,
      ecoPoints: 200,
      reporterName: 'Jerron J.',
      timeAgo: '2 hours ago',
      brandsDetected: ['Coca-Cola', 'Pepsi', 'Unbranded'],
      emoji: '🚨',
    ),
    OceanMapMarker(
      id: 'p2',
      title: 'Changi Beach Park',
      subtitle: 'Fishing net debris',
      position: LatLng(1.3875, 103.9877),
      type: MarkerType.pollution,
      severity: PollutionSeverity.high,
      status: ReportStatus.cleanupScheduled,
      wasteTypes: [WasteType.fishingNets, WasteType.cans],
      estimatedWasteKg: 78,
      volunteers: 12,
      ecoPoints: 150,
      reporterName: 'AquaHero99',
      timeAgo: '5 hours ago',
      brandsDetected: ['Unbranded'],
      emoji: '⚠️',
    ),
    OceanMapMarker(
      id: 'p3',
      title: 'Pasir Ris Beach',
      subtitle: 'Cigarette butts & cans',
      position: LatLng(1.3811, 103.9497),
      type: MarkerType.pollution,
      severity: PollutionSeverity.medium,
      status: ReportStatus.pending,
      wasteTypes: [WasteType.cigaretteButts, WasteType.cans],
      estimatedWasteKg: 22,
      volunteers: 0,
      ecoPoints: 75,
      reporterName: 'CoralSaver',
      timeAgo: 'Yesterday',
      brandsDetected: [],
      emoji: '⚠️',
    ),
    OceanMapMarker(
      id: 'p4',
      title: 'Sentosa Cove',
      subtitle: 'Food wrappers cleaned',
      position: LatLng(1.2494, 103.8303),
      type: MarkerType.pollution,
      severity: PollutionSeverity.cleaned,
      status: ReportStatus.completed,
      wasteTypes: [WasteType.foodWrappers, WasteType.plasticBags],
      estimatedWasteKg: 34,
      volunteers: 24,
      ecoPoints: 50,
      reporterName: 'BeachGuard7',
      timeAgo: '3 days ago',
      brandsDetected: ['McDonald\'s', 'KFC'],
      emoji: '✅',
    ),
    OceanMapMarker(
      id: 'p5',
      title: 'Marina South Pier',
      subtitle: 'Plastic bag clusters',
      position: LatLng(1.2718, 103.8634),
      type: MarkerType.pollution,
      severity: PollutionSeverity.low,
      status: ReportStatus.verified,
      wasteTypes: [WasteType.plasticBags, WasteType.glass],
      estimatedWasteKg: 8,
      volunteers: 0,
      ecoPoints: 40,
      reporterName: 'OceanWatch',
      timeAgo: '4 hours ago',
      brandsDetected: [],
      emoji: '🟡',
    ),
    // ── Cleanup events ──
    OceanMapMarker(
      id: 'c1',
      title: 'Sentosa Beach Cleanup',
      subtitle: 'Sat, May 17 • 8:00 AM',
      position: LatLng(1.2512, 103.8257),
      type: MarkerType.cleanup,
      volunteers: 38,
      ecoPoints: 100,
      emoji: '🧹',
      eventDate: 'Sat, May 17 • 8:00 AM',
    ),
    OceanMapMarker(
      id: 'c2',
      title: 'Marina Bay Shore Drive',
      subtitle: 'Sun, May 18 • 7:30 AM',
      position: LatLng(1.2832, 103.8607),
      type: MarkerType.cleanup,
      volunteers: 55,
      ecoPoints: 100,
      emoji: '🧹',
      eventDate: 'Sun, May 18 • 7:30 AM',
    ),
    // ── Recycling bins ──
    OceanMapMarker(
      id: 'r1',
      title: 'East Coast Recycling Hub',
      subtitle: 'Accepts: Plastic, Glass, Metal',
      position: LatLng(1.3100, 103.9200),
      type: MarkerType.recycling,
      emoji: '♻️',
    ),
    OceanMapMarker(
      id: 'r2',
      title: 'Changi Village Bin',
      subtitle: 'Open 24 hrs',
      position: LatLng(1.3900, 103.9900),
      type: MarkerType.recycling,
      emoji: '♻️',
    ),
    OceanMapMarker(
      id: 'r3',
      title: 'Pasir Ris Eco Point',
      subtitle: 'Accepts: Plastic, Paper',
      position: LatLng(1.3720, 103.9440),
      type: MarkerType.recycling,
      emoji: '♻️',
    ),
  ];

  // Heatmap positions for pollution intensity
  static const List<LatLng> heatmapPoints = [
    LatLng(1.3008, 103.9150),
    LatLng(1.3040, 103.9160),
    LatLng(1.2990, 103.9130),
    LatLng(1.3875, 103.9877),
    LatLng(1.3850, 103.9860),
    LatLng(1.3811, 103.9497),
    LatLng(1.2494, 103.8303),
    LatLng(1.2718, 103.8634),
    LatLng(1.2832, 103.8607),
  ];
}
